$ErrorActionPreference = "Stop"

Write-Host "🚧 Starting Deployment Build..." -ForegroundColor Cyan

# 1. Build the Next.js project
# Script is now inside 'web' (the repo root), so just run here.
Write-Host "Building Next.js project..." -ForegroundColor Gray
npx next build

if ($LASTEXITCODE -ne 0) {
    Write-Error "Build failed!"
    exit 1
}

# 2. Prepare docs folder
Write-Host "Cleaning previous deployment..." -ForegroundColor Gray
if (Test-Path "docs") {
    Remove-Item "docs" -Recurse -Force
}
# 'out' is generated by next build with output: export
if (Test-Path "out") {
    Rename-Item "out" "docs"
} else {
    Write-Error "Build output 'out' not found!"
    exit 1
}

# 3. Create 404.html for SPA routing
Write-Host "Creating 404.html for SPA fallback..." -ForegroundColor Gray
Copy-Item "docs\index.html" "docs\404.html" -Force

# 4. Git Push
Write-Host "Committing and Pushing..." -ForegroundColor Gray
git add .
git commit -m "Deploy: Automated build update"
git push

Write-Host "✅ Deployment Complete!" -ForegroundColor Green
